package tools.springfactories;

import java.io.IOException;
import java.io.InputStream;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeMap;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/** Usage: SpringFactoriesMerger <output> <jar>... */
public final class SpringFactoriesMerger {

  private static final String ENTRY = "META-INF/spring.factories";

  public static void main(String[] args) throws IOException {
    if (args.length < 1) {
      throw new IllegalArgumentException("usage: SpringFactoriesMerger <output> <jar>...");
    }
    Map<String, Set<String>> merged = new TreeMap<>();
    for (int i = 1; i < args.length; i++) {
      if (!args[i].endsWith(".jar")) {
        continue;
      }
      try (ZipFile zip = new ZipFile(args[i])) {
        ZipEntry entry = zip.getEntry(ENTRY);
        if (entry == null) {
          continue;
        }
        Properties props = new Properties();
        try (InputStream in = zip.getInputStream(entry)) {
          props.load(in);
        }
        for (String key : props.stringPropertyNames()) {
          Set<String> values = merged.computeIfAbsent(key, k -> new LinkedHashSet<>());
          for (String value : props.getProperty(key).split(",")) {
            if (!value.trim().isEmpty()) {
              values.add(value.trim());
            }
          }
        }
      }
    }
    try (Writer out = Files.newBufferedWriter(Paths.get(args[0]), StandardCharsets.ISO_8859_1)) {
      out.write("# Generated by //tools/springfactories:merger. Do not edit.\n");
      for (Map.Entry<String, Set<String>> e : merged.entrySet()) {
        out.write(e.getKey());
        out.write("=\\\n  ");
        out.write(String.join(",\\\n  ", e.getValue()));
        out.write("\n\n");
      }
    }
  }

  private SpringFactoriesMerger() {}
}
